export default {
  header: document.querySelector('#header'),
  home: document.querySelector('#home'),
  about: document.querySelector('#about'),
  abilities: document.querySelector('#abilities'),
  services: document.querySelector('#services'),
  stats: document.querySelector('#stats'),
  portfolio: document.querySelector('#portfolio'),
  footer: document.querySelector('#footer'),
  portfolio: document.querySelector('#portfolio'),
  testimonials: document.querySelector('#testimonials'),
  blog: document.querySelector('#blog'),
  contact: document.querySelector('#contact'),
  footer: document.querySelector('#footer'),
};
